config/routes.rb
Rails.application.routes.draw do
  root to: 'locations#index'
  resources :locations, only: %w(show create)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  GEOCODER_STREET_SERVICES_LIST = %i[nominatim dstk esri]

  geocoded_by :address, lookup: lambda{ |obj| obj.lookup.to_sym }

  def address
    [street, city, state, country, zip].compact.join(', ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
  end

  def create
    result = LocationsImport.call(file: params[:file])

    if result.success?
      redirect_to :root, notice: 'Success!'
    else
      redirect_to :root, alert: result.error
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/views/layouts/_alert.html.erb
<div class="row">
  <div class="col">
    <% flash.each do |key, value| %>
      <div class="alert <%= alert_class_for(key) %>">
        <a href="#" data-dismiss="alert" class="close">×</a>
        <ul class="nobullets" >
          <li><%= value.html_safe %></li>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class='navbar'>
  <a class='navbar-brand' href='/'>Home</a>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelbookRubyOnRailsTestTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class='container'>
      <%= render 'layouts/nav' %>
      <%= render 'layouts/alert', flash: flash %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/locations/_form.html.erb
<div class="location-form">
  <%= form_tag locations_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= button_tag 'Import from CSV', class: 'btn btn-primary center-block' %>
  <% end %>
</div>

app/views/locations/index.html.erb
<h1 class='text-center'>
  Import locations from CSV file.
</h1>

<div class="row text-center">
  <div class="col">
    <%= render 'form' %>
  </div>
</div>

<div class="row">
  <div class="col">
    <ul class="list-group list-group-flush">
      <% @locations.each do |location| %>
        <li class="list-group-item"><%= link_to location.address, location %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/locations/show.html.erb
<div class="container show-page-container">
  <div class="row">
    <div class="col">
      <div class="panel panel-primary ">
        <div class="panel-heading">
          <h3 class="panel-title">
            <span class="glyphicon glyphicon-map-marker"></span>
            <%= @location.address %>
          </h3>
        </div>
        <div class="panel-body">
          <% if @location.geocoded? %>
            <%= content_tag(:iframe, '', src: "https://www.google.com/maps/embed/v1/place?q=#{@location.latitude},#{@location.longitude}&key=#{ENV['GOOGLE_MAPS_KEY']}", width: '100%', height: 500, frameborder: 0) %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>